version: "3"

services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: ${INFLUXDB_CONTAINER_NAME}-${INFLUXDB_VERSION}
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
    read_only: true
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: ${GF_CONTAINER_NAME}-${GRAFANA_VERSION}
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    read_only: true
  # server:
  #   image: server:${SERVER_VERSION}
  #   container_name: ${SERVER_CONTAINER_NAME}-${SERVER_VERSION}
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     - influxdb
  #     - grafana
  #   environment:
  #     - name=value
  #   read_only: true
  # frontend:
  #   image: frontend:${FRONTEND_VERSION}
  #   container_name: ${FRONTEND_CONTAINER_NAME}-${FE_VERSION}
  #   ports:
  #     - "8866:8866"
  #   depends_on:
  #     - server
  #   environment:
  #     - name=value
  #   read_only: true