version: "3"

services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: ${INFLUXDB_CONTAINER}-${INFLUXDB_VERSION}
    ports:
      - ${INFLUXDB_PORT}
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: ${GF_CONTAINER}-${GRAFANA_VERSION}
    ports:
      - ${GF_PORT}
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  frontend:
    image: ${FE_IMAGE}:${FE_VERSION}
    container_name: ${FE_CONTAINER}-${FE_VERSION}
    ports:
      - ${FE_PORT}
    environment:
       - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    # volumes:
    #   - ../frontend/:/app
    depends_on:
      - influxdb
      - grafana