version: "3"

services:
  influxdb:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: ${INFLUXDB_CONTAINER_NAME}-${INFLUXDB_VERSION}
    ports:
      - ${INFLUXDB_PORT}
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: ${GF_CONTAINER_NAME}-${GRAFANA_VERSION}
    ports:
      - ${GF_PORT}
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  frontend:
    build:
      context: ../frontend
      dockerfile: ${FE_DOCKERFILE_PATH}
    image: frontend:${FE_VERSION}
    container_name: ${FE_CONTAINER_NAME}-${FE_VERSION}
    ports:
      - ${FE_PORT}
    volumes:
      - ../frontend:/app
