name: Main Branch Workflow

on:
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"

      - name: 📦 Setting up pnpm
        run: npm install -g pnpm && pnpm install

      - name: 🧪 Run unit tests and check coverage
        run: pnpm test:unit:coverage

      - name: 🐳 Build production Docker image
        run: docker build -f Dockerfile.prod -t visual-flux-frontend-prod .

      - name: 💻 Run e2e tests
        run: docker run visual-flux-frontend-prod pnpm test:e2e:prod

      - name: 📃 Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: 🚀 Push image to registry
        run: echo "Push to registry command here"
